In [1]:
import numpy as np #numpy kütüphanesini np takma adı ile projeye dahil ediyoruz

In [22]:
dizi=np.full((4,3),5)
dizi #np.full((satir,sütun),eleman) olarak yazar

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [3]:
#yeni bir numpy dizisi oluşturuyoruz
np.array([1,2,3])

array([1, 2, 3])

In [4]:
#oluşturduğumuz diziyi bir değişkene aktarıyoruz
dizi=np.array(["elma","erik","iğde"])

In [21]:
dizi

array([1, 2, 3])

In [20]:
dizi=np.array([1,2,3])
#normal 1, 2, 3 diye yazar
dizi

array([1, 2, 3])

In [18]:
dizi=np.array([1,2,3.14])
#ondalıklı olarak yazar
dizi

array([1.  , 2.  , 3.14])

In [12]:
dizi.dtype #dizinin değişken türünü verir.
#numpy dizilerinde elemanların hepsi aynı türdendir

dtype('float64')

In [38]:
dizi=np.array([1,2,3.14], dtype=int)
# 3.14ü ondalıklı sayıyı tam sayıya çevirir
dizi

array([1, 2, 3])

In [40]:
dizi=np.random.randint(0,10,(5,7),dtype=int)
dizi
#5 satır 7 sütundan oluşan rastgele sayılardan oluşan int türünde bir değişken oluşturur

array([[5, 2, 1, 1, 4, 5, 0],
       [2, 4, 1, 6, 1, 9, 4],
       [3, 6, 5, 4, 8, 8, 1],
       [5, 3, 9, 9, 8, 7, 8],
       [3, 9, 7, 0, 0, 2, 9]])

In [41]:
#bir boyutlu dizi oluşturma
birboyut=np.array([1,2,3,4])
#iki boyutlu dizi oluşturma
ikiboyut=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [42]:
birboyut

array([1, 2, 3, 4])

In [43]:
ikiboyut

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
np.zeros(7)
#7 sıfırdan olusan tek boyutlu dizi 

array([0., 0., 0., 0., 0., 0., 0.])

In [45]:
np.zeros((2,3),dtype=int)
#sıfırdan oluşan 2 boyutlu int dizi oluştrur

array([[0, 0, 0],
       [0, 0, 0]])

In [47]:
np.ones(3)
# 3 tane 1 yazar

array([1., 1., 1.])

In [48]:
np.full((4,3),5)
# 5 sayıdan oluşan 2*3 lük dizi

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [49]:
np.arange(2,22,5)
#başlangıç , bitiş ve artış değerine göre dizi

array([ 2,  7, 12, 17])

In [51]:
np.linspace(2,10,num=7)
# başlangıç ve bitis değeri aralığında belirtilen miktarda eşit aralık

array([ 2.        ,  3.33333333,  4.66666667,  6.        ,  7.33333333,
        8.66666667, 10.        ])

In [52]:
np.random.randint(0,10,5)
#0-10 aralığında rastgele 5 sayıdan oluşan bir boyut dizi

array([3, 3, 6, 6, 2])

In [54]:
np.random.randint(0,10,(5,2))
# 0-10 aralığında 5*2 rastgele sayıdan oluşan 2 boyutlu dizi

array([[5, 8],
       [9, 8],
       [6, 9],
       [4, 8],
       [6, 4]])

In [55]:
#dizilerrin eleman sayısını öğrenmek için shape komutu kullanılır
dizi=np.array([[1,2,3,4],[5,6,7,8],[9,101,11,12]])
dizi.shape

(3, 4)

In [56]:
#ndim dizi boyutunu öğrenmek için kullanılır
dizi.ndim

2

In [58]:
#size dizideki toplam eleman sayısını gösterir
dizi.size

12

In [59]:
dizi.itemsize
#dizideki her bir eleman bayt cinsinden değeri verir

4