In [1]:
import numpy as np #nump np adı ile eklendi
np.array([1,2,3]) #np kullanılarak liste oluşturuldu

array([1, 2, 3])

In [2]:
a=np.array([1,2,3])

In [3]:
dizi=np.array([1,2,3,3.14])
dizi

array([1.  , 2.  , 3.  , 3.14])

In [9]:
dizi=np.array([1,2,3,3.14],dtype=int)
dizi

array([1, 2, 3, 3])

In [24]:
birboyut=np.array([1,2,3])
birboyut #tek boyutlu dizi

array([1, 2, 3])

In [25]:
ikiboyut = np.array([[1,2,3], [4,5,6]])
ikiboyut #iki boyutlu dizi

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
ucboyut= np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])
ucboyut #üç boyutlu dizi


array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [13]:
np.zeros(5) #sıfırdan oluşan dize

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((4,3)) #sıfırdan oluşan dize

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.zeros((4,3),dtype=int) #sıfırdan oluşan dize

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [27]:
np.ones(5) #tek tek dize oluşturur

array([1., 1., 1., 1., 1.])

In [28]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
np.ones((4,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [30]:
np.full((4,3),10) #full dize oluşturur

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [31]:
np.arange(1,30,2) #başlangıç, bitiş ve artış değerleri

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [32]:
np.linspace(0, 10, num=5) #belirli bir aralıkta eşit aralıklı sayılar

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [33]:
np.random.randint(0,10,5) #belirli bir aralıkta rastgele sayılar

array([2, 7, 4, 4, 4])

In [34]:
np.random.randint(0,10,(4,3)) 

array([[2, 0, 0],
       [9, 9, 0],
       [9, 7, 4],
       [3, 2, 6]])